// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: insertSize.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertSize = `-- name: InsertSize :one
INSERT INTO size (id, product_id, size, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, size, quantity
`

type InsertSizeParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Size      string
	Quantity  int32
}

func (q *Queries) InsertSize(ctx context.Context, arg InsertSizeParams) (Size, error) {
	row := q.db.QueryRowContext(ctx, insertSize,
		arg.ID,
		arg.ProductID,
		arg.Size,
		arg.Quantity,
	)
	var i Size
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.Quantity,
	)
	return i, err
}
