// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: selectItems.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllItems = `-- name: GetAllItems :many
SELECT item.id, item.name, item.brand, item.price, item.available, item.url, size.size, size.quantity
FROM item JOIN size ON item.id = size.product_id
`

type GetAllItemsRow struct {
	ID        uuid.UUID
	Name      string
	Brand     string
	Price     string
	Available bool
	Url       string
	Size      string
	Quantity  int32
}

func (q *Queries) GetAllItems(ctx context.Context) ([]GetAllItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllItemsRow
	for rows.Next() {
		var i GetAllItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Price,
			&i.Available,
			&i.Url,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllItemsWithoutSizes = `-- name: GetAllItemsWithoutSizes :many
SELECT id, name, brand, price, available, url, last_check FROM item WHERE available = true
`

func (q *Queries) GetAllItemsWithoutSizes(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemsWithoutSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Price,
			&i.Available,
			&i.Url,
			&i.LastCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByBrand = `-- name: GetItemsByBrand :many
SELECT item.id, item.name, item.brand, item.price, item.available, item.url, size.size, size.quantity
FROM item JOIN size ON item.id = size.product_id
WHERE brand = $1
`

type GetItemsByBrandRow struct {
	ID        uuid.UUID
	Name      string
	Brand     string
	Price     string
	Available bool
	Url       string
	Size      string
	Quantity  int32
}

func (q *Queries) GetItemsByBrand(ctx context.Context, brand string) ([]GetItemsByBrandRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByBrand, brand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByBrandRow
	for rows.Next() {
		var i GetItemsByBrandRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Price,
			&i.Available,
			&i.Url,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByBrandAndMaxPrice = `-- name: GetItemsByBrandAndMaxPrice :many
SELECT item.id, item.name, item.brand, item.price, item.available, item.url, size.size, size.quantity
FROM item JOIN size ON item.id = size.product_id
WHERE brand = $1 AND price <= $2
`

type GetItemsByBrandAndMaxPriceParams struct {
	Brand string
	Price string
}

type GetItemsByBrandAndMaxPriceRow struct {
	ID        uuid.UUID
	Name      string
	Brand     string
	Price     string
	Available bool
	Url       string
	Size      string
	Quantity  int32
}

func (q *Queries) GetItemsByBrandAndMaxPrice(ctx context.Context, arg GetItemsByBrandAndMaxPriceParams) ([]GetItemsByBrandAndMaxPriceRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByBrandAndMaxPrice, arg.Brand, arg.Price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByBrandAndMaxPriceRow
	for rows.Next() {
		var i GetItemsByBrandAndMaxPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Price,
			&i.Available,
			&i.Url,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByMaxPrice = `-- name: GetItemsByMaxPrice :many
SELECT item.id, item.name, item.brand, item.price, item.available, item.url, size.size, size.quantity
FROM item JOIN size ON item.id = size.product_id
WHERE price <= $1
`

type GetItemsByMaxPriceRow struct {
	ID        uuid.UUID
	Name      string
	Brand     string
	Price     string
	Available bool
	Url       string
	Size      string
	Quantity  int32
}

func (q *Queries) GetItemsByMaxPrice(ctx context.Context, price string) ([]GetItemsByMaxPriceRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByMaxPrice, price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByMaxPriceRow
	for rows.Next() {
		var i GetItemsByMaxPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Price,
			&i.Available,
			&i.Url,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByName = `-- name: GetItemsByName :many
SELECT item.id, item.name, item.brand, item.price, item.available, item.url, size.size, size.quantity
FROM item JOIN size ON item.id = size.product_id
WHERE name = $1
`

type GetItemsByNameRow struct {
	ID        uuid.UUID
	Name      string
	Brand     string
	Price     string
	Available bool
	Url       string
	Size      string
	Quantity  int32
}

func (q *Queries) GetItemsByName(ctx context.Context, name string) ([]GetItemsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByNameRow
	for rows.Next() {
		var i GetItemsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Price,
			&i.Available,
			&i.Url,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
